const menuList = [
    {
        title: '首页',
        key:"/admin/home"
    },
    {
        title:"UI",
        key:"/admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/button"
            },
            {
                title:"弹窗",
                key:"/admin/ui/modals"
            },
            {
                title:"Loading",
                key:"/admin/ui/modals"
            }
        ]
    },
    {   title:"form表单",
        key:"/admin/form",
        children:[
            {
                title:"登录",
                key:"/admin/form/login"
            },
            {
                title:"注册",
                key:"/admin/form/register"
            }
        ]
    },
    {
        title:"表格",
        key:"/admin/table",
        children:[
            {
                title:"基础表格",
                key:"/admin/table/basic"
            },
            {
                title:"高级表格",
                key:"/admin/table/height"
            }
        ]
    },
    {
        title:"订单管理",
        key:"/admin/order"
    }
]
export default menuList